[tool.ruff.lint]
# select python version to use to check
line-length = 100
target-version = "py312"

# Enabled rules
select = [
     "B",  # bugbear: security warnings
     "E",  # pycodestyle
     "F",  # pyflakes
     "UP",  # alert you when better syntax is available in your python version
     "RUF",  # the ruff developer's own rules
]
