blank_issues_enabled: false
contact_links:
  - name: Dynamic Energy Cost Community Support
    url: https://community.home-assistant.io/t/dynamic-energy-cost/
    about: Please ask and answer questions here.
