# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DEFAULT_PYTHON: "3.13"  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
        
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt  
    - name: Test with pytest
      run: |
        pytest

     
