name: Renovate Bot
on:
  # Run at odd times to avoid overlap with too many other workflows on GitHub Actions
  # note github actions cron is in UTC so this is 20:12pm every thursday.
  schedule:
    - cron: "36 05 * * TUE"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
