name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./custom_components/dynamic_energy_cost"
          args: "check --fix"
      - name: ruff format
        uses: astral-sh/ruff-action@v3
        with:
          src: "./custom_components/dynamic_energy_cost"
          args: "format"
