name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install ruff
        uses: astral-sh/ruff-action@v3
        env:
          LOG_LEVEL: debug
      - name: run ruff 
        run: |
         ruff check --fix
         ruff format
         
