name: Ruff Linter
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DEFAULT_PYTHON: "3.12" 
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: |
          ruff check --fix --verbose
          ruff format --verbose
         
